### ISSUE TITLE
Failed to start Local session service for the Pop System Updater.

### ISSUE THREAD

**Issue by nerdboy4200** [pop-os/system-updater#16]
These entries are spamming my systemd logs ever since I installed the latest pop-system-updater:

```
May 14 12:48:49 lagos pop-system-updater[40163]: Error: service must be launched from either root or a desktop user
May 14 12:48:49 lagos systemd[1255]: com.system76.SystemUpdater.Local.service: Main process exited, code=exited, status=1/FAILURE
May 14 12:48:49 lagos systemd[1255]: com.system76.SystemUpdater.Local.service: Failed with result 'exit-code'.
May 14 12:48:49 lagos systemd[1255]: Failed to start Local session service for the Pop System Updater.
May 14 12:48:49 lagos systemd[1255]: com.system76.SystemUpdater.Local.service: Scheduled restart job, restart counter is at 402.
May 14 12:48:49 lagos systemd[1255]: Stopped Local session service for the Pop System Updater.
May 14 12:48:49 lagos systemd[1255]: Starting Local session service for the Pop System Updater...
```

This started after I got an update to version `0.1.0~1651702806~21.10~b49b23a`.

This is a **very** high priority issue as it is slamming updates in my log every 2-20 seconds and there isn't a way to roll BACK to a version without this bug without building it oneself. This is going to kill systms that have SSDs for their main disk.

**Comment by nerdboy4200** [comment]
Looking at the log entry in depth - I noticed this:
```
    _PID=1255
...
    _UID=111
    _GID=118
```

which co-incides with:
```
gdm         1255  0.0  0.0  15916  9412 ?        Ss   11:40   0:01 /lib/systemd/systemd --user
```

and this:
```
$ id 111
uid=111(gdm) gid=118(gdm) groups=118(gdm)
$
```

which means that gdm session is trying to launch the updater since its starting as a "user" and therefore its triggering the service and with your new changes to the code - it triggers the error.

**Comment by mmstick** [comment]
There hasn't been any changes to the code since shortly after release day

**Comment by nerdboy4200** [comment]
I think this bug comes from 5fac558a11ce4a486601d78042bf481231315130 in daemon/src/main.rs

Do we know if the Err function (procedure? method?) (sorry - not a rust person so my knowledge of things comes from other languages) triggers a return code of 1 if you don't catch it - which the .services Restart=Always line in the user com.system76.SystemUpdater.Local.service triggers a restart because of the fail?

My current workaround consists of adding:
```
[Service]
Restart=no
```
to /var/lib/gdm3/.config/systemd/user/com.system76.SystemUpdater.Local.service.d/override.conf to force the process to NOT start after a failure as the gdm user (since they are not a "real" user). (I have to reboot to make that change take hold - which is fine)

**Comment by mmstick** [comment]
It does. The service should exit without error if started from a non-desktop account.

**Comment by nerdboy4200** [comment]
Except - due to your config of forcefully restarting - it tries to restart over and over and over:

```
$ journalctl -b -1|grep pop-system-updater|cut -d: -f1,2|sort -n|uniq -c
     28 May 14 11:40
      6 May 14 11:41
      6 May 14 11:42
      6 May 14 11:43
      6 May 14 11:44
      6 May 14 11:45
      6 May 14 11:46
      5 May 14 11:47
      6 May 14 11:48
      6 May 14 11:49
      6 May 14 11:50
      6 May 14 11:51
      6 May 14 11:52
      6 May 14 11:53
      5 May 14 11:54
      6 May 14 11:55
      6 May 14 11:56
      6 May 14 11:57
      6 May 14 11:58
      6 May 14 11:59
      6 May 14 12:00
      5 May 14 12:01
      6 May 14 12:02
      6 May 14 12:03
      6 May 14 12:04
      6 May 14 12:05
      6 May 14 12:06
      6 May 14 12:07
      5 May 14 12:08
      6 May 14 12:09
      6 May 14 12:10
      6 May 14 12:11
      6 May 14 12:12
      6 May 14 12:13
      5 May 14 12:14
      6 May 14 12:15
      6 May 14 12:16
      6 May 14 12:17
      6 May 14 12:18
      6 May 14 12:19
     10 May 14 12:20
     26 May 14 12:21
      6 May 14 12:22
      6 May 14 12:23
     22 May 14 12:24
     16 May 14 12:25
      6 May 14 12:26
      6 May 14 12:27
      9 May 14 12:28
     31 May 14 12:29
      6 May 14 12:30
      6 May 14 12:31
      6 May 14 12:32
      6 May 14 12:33
      6 May 14 12:34
      5 May 14 12:35
      6 May 14 12:36
      6 May 14 12:37
      6 May 14 12:38
      6 May 14 12:39
      6 May 14 12:40
      6 May 14 12:41
      5 May 14 12:42
      6 May 14 12:43
     30 May 14 12:44
      6 May 14 12:45
      6 May 14 12:46
      6 May 14 12:47
      6 May 14 12:48
      5 May 14 12:49
      6 May 14 12:50
      6 May 14 12:51
      6 May 14 12:52
      6 May 14 12:53
      6 May 14 12:54
      5 May 14 12:55
      6 May 14 12:56
      6 May 14 12:57
      6 May 14 12:58
      6 May 14 12:59
      6 May 14 13:00
     17 May 14 13:01
      5 May 14 13:02
      6 May 14 13:03
      6 May 14 13:04
      6 May 14 13:05
     19 May 14 13:06
      6 May 14 13:07
      9 May 14 13:08
      5 May 14 13:09
      6 May 14 13:10
      6 May 14 13:11
      6 May 14 13:12
      9 May 14 13:13
      6 May 14 13:14
      6 May 14 13:15
      5 May 14 13:16
      6 May 14 13:17
      6 May 14 13:18
      6 May 14 13:19
      6 May 14 13:20
      6 May 14 13:21
      6 May 14 13:22
      5 May 14 13:23
      6 May 14 13:24
      6 May 14 13:25
      6 May 14 13:26
      6 May 14 13:27
      6 May 14 13:28
      6 May 14 13:29
      5 May 14 13:30
      5 May 14 13:31
$
```
so that is 5-6 times per MINUTE for an "account" that should not need to run this process - but since your user script says to force a restart every time it fails on exit and keeps restrting - thereby filling the logs.

I'm just looking for 1 line there  - in actuallity - it spits out this for each of those:
```
May 14 13:28:37 lagos pop-system-updater[55988]: Error: service must be launched from either root or a desktop user
May 14 13:28:37 lagos systemd[1255]: com.system76.SystemUpdater.Local.service: Main process exited, code=exited, status=1/FAILURE
May 14 13:28:37 lagos systemd[1255]: com.system76.SystemUpdater.Local.service: Failed with result 'exit-code'.
May 14 13:28:37 lagos systemd[1255]: Failed to start Local session service for the Pop System Updater.
May 14 13:28:38 lagos systemd[1255]: com.system76.SystemUpdater.Local.service: Scheduled restart job, restart counter is at 635.
May 14 13:28:38 lagos systemd[1255]: Stopped Local session service for the Pop System Updater.
May 14 13:28:38 lagos systemd[1255]: Starting Local session service for the Pop System Updater...
```

Wouldn't it make more sense to either prevent the restart since its constantly restarting - or prevent this non-user from starting the daemon in the first place?

**Comment by mmstick** [comment]
There's no need to angrily repeat yourself. Just filing an issue is good enough for me to address on Monday. If you want to submit a PR you may.

**Comment by nerdboy4200** [comment]
Sorry for the update - I didn't think it sounded angry.

I don't know enough to be able to help with a bug fix - otherwise I'd post something.

**Comment by mmstick** [comment]
In this case, the application should return Ok(()) instead of an error

**Comment by mmstick** [comment]
The systemd service should also be set to only restart on failure
