### ISSUE TITLE
[21.10] Config file being populated as Daily instead of Weekly

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/system-updater#4]
After installing the most recent 21.10 iso, system-updater is pulled in via pop-upgrade updates, and the config file for update notifications is defaulting to Daily. If I delete the config file and reboot, then it does get regenerated to Weekly. Not yet sure where the initial Daily value is coming from.

**Comment by jackpot51** [comment]
We released a version with Daily, and the config file is created as soon as possible, so I don't think there is a sane way to fix this other than hoping most people did not get that version.

**Comment by jacobgkau** [comment]
If the most recent 21.10 iso contains an older version defaulting to Daily and that's what's causing the issue to show up on a fresh install, then we might want to try and release new 21.10 iso's.

**Comment by jacobgkau** [comment]
Inspecting `/var/log/apt/history.log` on an affected system, it looks like `pop-system-updater` was not present on the iso and was installed at version 500a384 (the lastest, with the new default) as its first version, so I'm not sure an older version is what's causing the issue.

**Comment by jackpot51** [comment]
@13r0ck can you look at this while you are looking at the updates on boot issue?

**Comment by 13r0ck** [comment]
This was determined not to be an issue
